View(exam_data)
num1 <- c(exam_data$Exam1)
num2 <- c(exam_data$Exam2)
min1 <- min(num1)
min2 <- min(num2)
max1 <- max(num1)
max2 <- max(num2)
mean1 <- mean(num1)
mean2 <- mean(num2)
middle1 <- median(num1)
middle2 <- median(num2)
var1 <- var(num1)
var2 <- var(num2)
ekhtelaf <- num1 - num2
quantiles <- quantile(ekhtelaf)
quantiles1 <- quantile(num1)
quantiles2 <- quantile(num2)
plot(ekhtelaf)
plot(num1)
plot(num2)

